export class DriverModel {
  public _id!: string; //generated by mongoDB
  public name!: string;
  public surname!: string;
  public phone!: number;
  public ongoing_orders!: number;
  public delivered_orders!: number;
  public canceled_orders!: number;
  constructor(model?: any) {
    Object.assign(this,model);
  }
}
