export class OrderModel {
    public _id!: string; // generated by mongoDB
    public address!: string;
    public street_number!: number;
    public zip_code!: number;
    public floor_level!: number;
    public volume!: number;
    public status!: string;
    public timestamp!: any;
    public time!: Date;
    public createdAt!: Date; // generated by mongoDB
    public updatedAt!: Date; // generated by mongoDB
    constructor(model?: any) {
      Object.assign(this, model);
    }
  
  }